on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest

    environment:
      name: PROD

    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node

      - uses: actions/setup-node@v3
        with:
          always-auth : true
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          scope: 'kawaii-japanese-nickname'
        env :
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run : npx can-npm-publish --verbose
      - run : ./scripts/main ./nicknames.txt ./data.json
      - run : npm diff
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run : npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
